###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://deepblue:3306/testdb
    username: testuser
    password: testuser
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
        ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
