server:
  port: 8080

spring:
  security:
    user:
      name: spring
      password: secret
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial

preference:
  top-page:
    list-length: 10
    checkd: true
  detail-page:
    list-length: 5
    checked: false

