server:
  port: 8080

spring:
  security:
    user:
      name: spring
      password: secret
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial

preference:
  top-page:
    list-length: 10
    checked: true
  detail-page:
    list-length: 5
    checked: false

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:

public-key: classpath:jwt.pub.key
private-key: classpath:jwt.key.p1
