server:
  port: 8080

spring:
  security:
    user:
      name: spring
      password: secret


preference:
  top-page:
    list-length: 10
    checkd: true
  detail-page:
    list-length: 5
    checked: false

